# Auto-generated by Polyphase editor on project open.
# Recorded engine path for addons in this project. Addon
# CMakeLists files walk up looking for this file and include
# it before their own POLYPHASE_PATH probe chain runs.
#
# Safe to commit: if the recorded path doesn't exist on the
# current machine (teammate with a different engine layout),
# this no-ops and the addon's own probe chain takes over.
if(NOT DEFINED POLYPHASE_PATH OR POLYPHASE_PATH STREQUAL "")
    if(EXISTS "/opt/polyphase/Polyphase.sln" OR EXISTS "/opt/polyphase/Polyphase.exe")
        set(POLYPHASE_PATH "/opt/polyphase")
    endif()
endif()
